"""Add owner_id to todos

Revision ID: cf10ec9f67d6
Revises: 0640e7d7cf9b
Create Date: 2025-08-27 17:01:16.352079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf10ec9f67d6'
down_revision: Union[str, Sequence[str], None] = '0640e7d7cf9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('owner_id', sa.Integer(), nullable=False,  server_default="1"))
    op.create_foreign_key('fk_todos_users',
    source_table='todos',
    referent_table='users',
    local_cols=['owner_id'],
    remote_cols=['id'],
    ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todos', type_='foreignkey')
    op.drop_column('todos', 'owner_id')
    # ### end Alembic commands ###
