"""Add owner_id to todos

Revision ID: f6adfd6a4f63
Revises: cf10ec9f67d6
Create Date: 2025-08-27 17:07:06.427960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6adfd6a4f63'
down_revision: Union[str, Sequence[str], None] = 'cf10ec9f67d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
